import Head from 'next/head'
import React from 'react'
import ReactPlayer from 'react-player'
import { About, Aims, Events, Learn, PageLayout, Solution, System, Tutor, Vision } from '@/components'

export default function about() {
  return (
    <>
        <Head>
        <title>About DALA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageLayout>
                  <About />
                  <Aims />
                  <Vision />
                  <Solution />
                  <Events />
                  <System />
                  <Learn />
                  <Tutor />
        </PageLayout>
      </main>
    </>
  )
}
