import Head from 'next/head'
import React from 'react'
import ReactPlayer from 'react-player'
import { PageLayout } from '@/components'

export default function about() {
  return (
    <>
        <Head>
        <title>About DALA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageLayout>
            <div className='w-[90%] m-auto'>
            <div className=''>
              <div className='md:hidden text-left pt-[138px] mb-[181px] '>
                      <h1 className='font-semibold text-[#1E1E1E] text-[32px] mb-[5px] '>About DALA</h1>
                      <p className='text-[16px] text-black  '>Learn more about DivineAssistants Learning Academy</p>
              </div>
                  <div className='hidden md:block md:rounded-[15px] md:w-[95%] md:m-auto md:mt-[76px] md:relative md:mb-[256px]   '>
                      <img src="/images/about-back.svg" alt="" />
                      <h1 className='font-semibold text-[75px] text-[#FAFAFA] absolute z-10 top-[37%] left-[37%]   '>About Us</h1>
                  </div>
            </div>
            <div className='bg-black mb-[40px] '>
            <video autoPlay loop>
               <source src="./videos/about-video.mp4"  />
            </video>    
            </div>
                <div className='mb-[40px] '>
                    <h1 className='text-[#1E1E1E] font-semibold text-[24px] mb-[5px] '>About Us</h1>
                    <p className='text-[#1E1E1E] text-[16px] '>
                    DALA is an incredible arm of DivineAssistants that came to life in 2023. It is a unique learning academy with a mission to provide quality training to youths in the tech space, promoting growth and development. The youth who complete the training program are provided with an opportunity to be apprentices with the company and potentially be retained. Since its inception, DALA has made significant strides towards its mission of developing young talent into tech leaders of tomorrow, providing them with a platform to make a lasting impression. Through this initiative, DivineAssistants is making a substantial contribution to the community by creating a better future for the youth and helping them reach their potential.
                    </p> 
                </div>
            </div>
            <div className='text-[20px] bg-[FAFAFA] shadow-[5px_5px_15px_rgba(0,0,0,0.1)] rounded-[5px] flex items-center gap-[29px] justify-around py-[20px] mb-[205px] '>
                <p><span className='font-semibold '>20k+</span> students</p>
                <p><span className='font-semibold '>70</span> Tutors</p>
                <p><span className='font-semibold '>150k+</span> courses</p>
            </div>
            <div className='w-[90%] m-auto '>
              <div className='w-fit m-auto mb-[40px]'>
              <img src="/images/Macbook-Pro.svg" alt="Laptop Display" />
              </div>
              <h2 className='font-semibold text-[24px] text-[#1E1E1E] '>Online and Video Based Learning Platform</h2>
              <p className=' text-[#1E1E1E] text-[16px] mb-[210px] '>DALA is a short video-based learning academy that offers administrative and business management programs. Our programs are designed to provide students with the knowledge and skills they need to successfully manage an organization or develop a business.

Our program curriculum covers crucial topics such as financial literacy, communication strategies, project management, problem solving, decision making and organizational development. We emphasize the importance of understanding the concepts of leadership, management styles, negotiation tactics and strategic planning. With our coursework, students can gain an understanding of how to increase productivity in their workplace while developing their own professional career paths. DALA provides a high-quality learning experience for our students with its short video lectures which are supplemented by assignments and assessments so that participants can measure their progress as they learn. The courses also include case studies from real-world scenarios where students can apply the concepts learned in class in practical scenarios.</p>
            </div>
            <div className='bg-[url("/images/about-back.svg")] mb-[202px] pb-[81px] '>
              <div className=' pt-[80px] w-[90%] m-auto text-[#FAFAFA] '>
                  <h2 className='font- semibold text-[24px] mb-[5px] '>Aims</h2>  
                  <p className='text-[16px] mb-[40px] '>DALA's aim is to help young people gain the skills and knowledge they need to build a career in technology that contributes to sustainable development. Through its innovative tech learning academy, DALA provides access to a broad range of courses, activities, and resources. In addition to providing a comprehensive learning environment, DALA also offers guidance and support to help youth understand the goal and reach their full potential. This includes counseling services, mentorship opportunities, and career advice. With its aim to empower youth with the right skills and resources, DALA is committed to helping individuals achieve their ambitions and contribute to a more sustainable future.</p>
                  <div className='rounded-[17px] w-[369px] h-[354px] pb-[81px] m-auto  '><img src="/images/about-lady.svg" alt="Divine Onyeleonu" className='w-contain h-fit' /></div>
              </div>
            </div>
            <div className='w-[90%] relative mb-[92px] '>
                <div className='w-[260px] h-[260px] rounded-[100%] border-4 border-[#004AAD] grid place-items-center m-auto '>
                   <div className='w-[250px] h-[250px] rounded-[100%] border-4 border-[#FAFAFA] grid place-items-center '>
                   <img src="/images/co-working.png" alt="" className='rounded-[100%] w-[240px] h-[240px]  '  />
                   </div>  
                </div>
                <div className='w-[160px] h-[160px] rounded-[100%] border-4 border-[#004AAD] grid place-items-center absolute top-[50%] left-[60%] '>
                   <div className='w-[150px] h-[150px] rounded-[100%] border-4 border-[#FAFAFA] grid place-items-center '>
                   <img src="/images/co-working.png" alt="" className='rounded-[100%] w-[140px] h-[140px]  '  />
                   </div>  
                </div>
            </div>
            <div className='w-[90%] m-auto text-[#1E1E1E] mb-[205px] '>
                <h2 className='text-[24px] font-semibold '>Vision Statement</h2>
                <p className='text-[16px]'>At DALA, our vision is to empower the youth to stay ahead of the curve and become a part of the rapidly advancing technology landscape. We provide them with tech skills to help them build a career where they can make valuable contributions in areas like sustainable development and business growth. Our goal is to equip them with the necessary knowledge and resources to be able to compete in the global technology market, as well as contribute to global growth and development. By providing them with the right training, we are helping to create a brighter future for our youth that will benefit all of us in the long run. Our vision is to create a world where everyone can access quality education and training, enabling them to pursue their goals and dreams.</p>
            </div>
            <div className='bg-[url("/images/about-back.svg")] mb-[271px] '>
            <div className=' pt-[80px] w-[90%] m-auto text-[#FAFAFA] '>
            <h2 className='font- semibold text-[24px] mb-[5px] '>The Problem</h2>  
                  <p className='text-[16px] mb-[40px] '>In my experience as a young person growing up in Africa, one thing has
been constant: there are never enough jobs available for the kids of the
neighbourhood. Many families have toiled to put their children through
elementary, secondary, and tertiary education, and yet even after all of
this, there are never enough jobs for the young. In nations like Nigeria,
where young people are struggling to find work, we have seen a
dramatic surge in fraud. Few retirees among the elderly have sufficient
pension money to support their desire to do so, and those who do are
unlikely to find work in their later years. For a very long period, this has
been a consistent situation throughout Africa.</p>
                <div className='flex items-center gap-[23px] mb-[40px] '>
                  <div className='w-[40%] border-2 border-[#FAFAFA] '></div>
                  <div className='w-[10%] border-2 border-[#FAFAFA]'></div>
                  <div className='w-[40%] border-2 border-[#FAFAFA]'></div>
                </div>
                <h2 className='font- semibold text-[24px] mb-[5px] '>Our Solution</h2>  
                  <p className='text-[16px] pb-[72px] '>We like to call our solution operation
"Bringing the Dollar Back Home."
The DivineAssistants Learning Academy is going to focus on providing
video-based learning programs for individuals in Africa.
DivineAssistants itself is a digital firm for business management.
DivineAssistants is a virtual support company that is dedicated to
bringing entrepreneurs virtual team services to help them handle their
day-to-day tasks remotely while they focus on handling their core
business growth.</p>
            </div>
            </div>
            <div className='w-[90%] m-auto text-[#1E1E1E] '>
                <h2 className='text-[24px] font-semibold  '>Events</h2>
                <p className='text-[16px] mb-[30px] '>The DALA project is an ambitious effort to provide quality education and training for the youths of Nigeria. In line with this vision, a fundraising event is scheduled to take place in Aug/Sep this year. This event will be an opportunity for potential donors to come forward and contribute their support for the cause of learning academy. It will also be a chance to spread awareness about the importance of investing in the growth and development of young people. The DALA project is dedicated to transforming the lives of Nigerian youths by equipping them with valuable skills and knowledge that will aid them in achieving success. We invite everyone to come forth and join us in our mission. We need your support to make this dream a reality.</p>
                <div className='w-[100%] relative mb-[272px] '>
                  <img src="/images/puzzle.svg" alt="DALA Roadmap" className='m-auto' />
                  <div className='bg-[#DA063F] w-[12.44px] h-[12.44px] rounded-[100%] absolute top-[0%] left-[15%] '></div>
                  <div className='bg-[#BF780E] w-[12.44px] h-[12.44px] rounded-[100%] absolute top-[10%] left-[95%] '></div>
                  <div className='bg-[#DBFF00] w-[12.44px] h-[12.44px] rounded-[100%] absolute top-[50%] left-[50%] '></div>
                  <div className='bg-[#DBFF00] w-[12.44px] h-[12.44px] rounded-[100%] absolute top-[48%] left-[0%] '></div>
                  <div className='bg-[#02CFC3] w-[12.44px] h-[12.44px] rounded-[100%] absolute top-[46%] left-[100%] '></div>
                  <div className='bg-[#8E049A] w-[12.44px] h-[12.44px] rounded-[100%] absolute bottom-[10%] left-[45%] '></div>
                  <div className='bg-[#157C20] w-[12.44px] h-[12.44px] rounded-[100%] absolute bottom-[0%] left-[95%] '></div>
                </div>

              <h2 className='font-semibold text-[24px] '>The System</h2>
              <p className='text-[16px] mb-[53px] '>All Graduates are required to work with DivineAssistants for a minimum of 18 months after graduation. This will allow
us to maintain our investment in them</p>
                <div className='w-[50%] text-center mb-[29px] '>
                  <div className='flex gap-[20.5px] items-center m-auto w-fit '>
                    <img src="/images/Book.svg" alt="Complete Course" />
                    <img src="/images/1.svg" alt="Step One" />
                    </div>
                  <p className='text- [16px] font-semibold'>Complete course</p>
                  <p className='text- [13px]'>The student enrolls on DALA and complete any course of his/her choice</p>
                </div>

              <div className='flex gap-[12px] mb-[53px] '>
                <div className='ml-[120px] '><img src="/images/left-stroke.svg" alt="" /></div>
              <div className='w-[50%] text-center'>
                  <div className='flex gap-[20.5px] items-center m-auto w-fit '>
                    <img src="/images/Book.svg" alt="Complete Course" />
                    <img src="/images/2.svg" alt="Step One" />
                    </div>
                  <p className='text- [16px] font-semibold'>Gets Onboarded into
DivineAssistants/Niile</p>
                  <p className='text- [13px]'>Upon graduation, each student will
be onboarded into DivineAssistants
or Niile based on their department</p>
                </div>
              </div>

              <div className='flex gap-[12px] mb-[53px] '>
              <div className='w-[50%] text-center'>
                  <div className='flex gap-[20.5px] items-center m-auto w-fit '>
                    <img src="/images/internship.svg" alt="Complete Course" />
                    <img src="/images/3.svg" alt="Step One" />
                    </div>
                  <p className='text- [16px] font-semibold'>Begin Internship</p>
                  <p className='text- [13px]'>The student enrolls on DALA and complete a
3-month internship with DivineAssistants.
</p>
                </div>
                <div className='mr-[120px] '><img src="/images/right-stroke.svg" alt="" /></div>
              </div>

              <div className='flex gap-[12px] mb-[53px] '>
              <div className='ml-[120px] '><img src="/images/left-stroke.svg" alt="" /></div>
              <div className='w-[50%] text-center'>
                  <div className='flex gap-[20.5px] items-center m-auto w-fit '>
                    <img src="/images/check-list.svg" alt="Complete Course" />
                    <img src="/images/4.svg" alt="Step One" />
                    </div>
                  <p className='text- [16px] font-semibold'>Evaluation</p>
                  <p className='text- [13px]'>After their three months probation is
over, each employee will receive their evaluation and may be hired full-time
depending on their performance.
</p>
                </div>
              </div>

              <div className='flex gap-[12px] mb-[53px] '>
              <div className='w-[50%] text-center'>
                  <div className='flex gap-[20.5px] items-center m-auto w-fit '>
                    <img src="/images/internship.svg" alt="Complete Course" />
                    <img src="/images/5.svg" alt="Step One" />
                    </div>
                  <p className='text- [16px] font-semibold'>Welcome Package</p>
                  <p className='text- [13px]'>If they pass, they receive their employee welcome package which
involves the company t-shirt, wifi, cup
and laptop (depending on budget).
</p>
                </div>
                <div className='mr-[120px] '><img src="/images/right-stroke.svg" alt="" /></div>
              </div>

              <div className='flex gap-[12px] mb-[53px] '>
              <div className='ml-[120px] '><img src="/images/left-stroke.svg" alt="" /></div>
              <div className='w-[50%] text-center'>
                  <div className='flex gap-[20.5px] items-center m-auto w-fit '>
                    <img src="/images/accredition.svg" alt="Complete Course" />
                    <img src="/images/6.svg" alt="Step One" />
                    </div>
                  <p className='text- [16px] font-semibold'>Certificate/Accredition</p>
                  <p className='text- [13px]'>All Graduates will receive a
certificate of completion after
they have successfully
completed their learning
program.
</p>
                </div>
              </div>

              <div className='flex gap-[12px] mb-[206px] '>
              <div className='w-[50%] text-center'>
                  <div className='flex gap-[20.5px] items-center m-auto w-fit '>
                    <img src="/images/incase-failure.svg" alt="Complete Course" />
                    <img src="/images/7.svg" alt="Step One" />
                    </div>
                  <p className='text- [16px] font-semibold'>Incase of Failure</p>
                  <p className='text- [13px]'>If they fail their evaluation, their
probation period may be extended
according to recommendation
</p>
                </div>
                <div className='mr-[120px] '><img src="/images/right-stroke.svg" alt="" /></div>
              </div>
            </div>
          <div className='bg-[url("/images/about-back.svg")] mb-[200px] pt-[74px] pb-[73px] '>
              <div className='flex gap-[38px] w-[90%] m-auto mb-[40px]  '>
              <div className=''>
                  <div className='rounded-t-[500px]  w-[163px] h-[221px] mb-[10px] '><img src="/images/tutor1.png" alt="Tutor" className='rounded-t-[500px]' /></div>
                  <div className='rounded-t-[500px] rounded-bl-[500px] w-[163px] h-[221px] '><img src="/images/tutor1.png" alt="Tutor" className='rounded-t-[500px] rounded-bl-[500px]' /></div>
              </div>
              <div className=''>
                  <div className='rounded-t-[500px] rounded-bl-[500px] w-[163px] h-[221px] mb-[10px] '><img src="/images/tutor1.png" alt="Tutor" className='rounded-t-[500px] rounded-bl-[500px]' /></div>
                  <div className='rounded-t-[500px]  w-[163px] h-[221px]  '><img src="/images/tutor1.png" alt="Tutor" className='rounded-t-[500px]' /></div>
              </div>
              </div>
              <div className='w-[90%] m-auto text-[#FAFAFA]'>
                  <p className='text-[28px] font-semibold mb-[10px] '>Learn variety of courses with our dedicated team of experienced mentors</p>
                  <button className='py-[18px] px-[33px] rounded-[100px] border-2 border-[#FAFAFA] text-[16px] '>Learn More</button>
              </div>
              
          </div>
          <div className='bg-[url("/images/about-back2.svg")] pt-[54px] pb-[54px] mb-[95px] '>
                  <div className='w-[90%] m-auto mb-[26px] text-center'>
                    <h2 className='text-[#004AAD] font-semibold text-[24px] mb-[26px] '>Becoming a DALA tutor in 5 easy steps</h2>
                    <p className='font-semibold  text-[13px] text-[#1E1E1E] mb-[26px] '>Click on the button below
Fill a form and an email will be sent shortly after
A meeting schedule between you and HR will be sent for evaluation
Upon successful evaluation, a Tutor Identification Code (TIC) will be sent to your email
Log In as a tutor <span className='text-[#004AAD]'>AND VOILA!!!</span></p>
                 <button className='font-semibold text-[16px] text-[#FAFAFA] py-[18px] px-[25px] rounded-[10px] bg-[#004AAD]  mb-[40px] m-auto  '>Become a DALA tutor</button>
                  </div>
                  <div className='flex items-center justify-between '>

                       <div className='rounded-[10px] w-[33px] h-[258px] '>
                          <img src="/images/tutor-side.png" alt="Become a tutor" className='w-[100%] h-[100%] rounded-[10px]' />
                        </div>

                        <div className='rounded-[10px] w-[278px] h-[258px] '>
                          <img src="/images/tutor3.png" alt="Become a tutor" className='w-[100%] h-[100%] rounded-[10px]' />
                        </div>

                        <div className='rounded-[10px] w-[33px] h-[258px] '>
                          <img src="/images/tutor-side2.png" alt="Become a tutor" className='w-[100%] h-[100%] rounded-[10px]' />
                        </div>
                  </div>
              </div>
        </PageLayout>
      </main>
    </>
  )
}
