import Head from "next/head";
import { NavBar } from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <section
          className="pt-[124px] bg-[#004AAD] h-[1026px] relative"
          style={{ overflow: "hidden" }}
        >
          <div
            className="w-[850px] h-[650px] bg-red-200 rounded-[50%] absolute"
            style={{ transform: "rotate(-50deg)", right: "-200px" }}
          ></div>
        </section>
      </main>
    </>
  );
}
